### PR TITLE
Adding mouse/trackball support.

### PR DESCRIPTION
**Pull request by iequalshane**
Note: Moving too quickly can wrap the movement counter between reads but this is the same behavior as MAME.

### CODE REVIEW

**Comment by sorgelig** [comment]
Is it possible to add workaround to limit amount of movements to prevent wrapping?

**Comment by iequalshane** [comment]
It's possible but this is supposedly the proper behavior. If you move around at normal rates it doesn't hit this. I wish I had access to the real cabinet to compare to be sure.

**Comment by iequalshane** [comment]
I haven't found someone with an original cabinet yet but I had someone compare the core against their AtGames Centipede cab and they said it behaved identical. Of course, that's probably just MAME under the hood.

**Comment by jstavats** [comment]
hi, is this trackball update in the release core version?

**Pull request merged**
